name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.3.0
  - pytest=8.4.1
  - scipy=1.15.3
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.20.1
