name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - hydra-core=1.3.2
  - matplotlib=3.10.3
  - pandas=2.3.0
  - pip=23.3.1
  - scikit-learn=1.3.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.20.1
